# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd3bc64122dc7bf2198d74c201fe60d4259be8aef9d50b450b2537a79d7ebf00dfe6cf59b0611c7738e09cef588b42a60062b6b1f19b48b6b641c9db861b6ce6

test:
  secret_key_base: c56c0afd43968f59bbf798a29e618d9ac03bff3d5736ebfa3be74bf3e7a505e05f40f0d6170f294408d3df208936a67d4b7d976ed276457710c0db39b053321c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
